### ISSUE TITLE
Static cache

### ISSUE THREAD

**Issue by mwagena** [duncanmcclean/cookie-notice#84]
### Description

When setting static cache to strategy 'full' you will notice that the cookie notice popup won't work. For some reason the cache works agains us, when setting the strategy to 'half', all is alright.

### Steps to reproduce

1. STATAMIC_STATIC_CACHING_STRATEGY=full
2. install cookie notice plugin
3. try to submit the notice form

### Environment

Environment
Laravel Version: 10.48.17
PHP Version: 8.1.27
Composer Version: 2.2.8
Environment: acceptance
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / daily, flare
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 3 (NL, EN, DE)
Stache Watcher: Enabled
Static Caching: full
Version: 5.17.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 5.2.3
duncanmcclean/cookie-notice: 9.1.0
withcandour/aardvark-seo: 5.0.0

**Comment by duncanmcclean** [comment]
I can't seem to reproduce this, using `full` or `half` static caching... the widget shows as expected.

Can you try switching back to full-measure caching, clearing the static cache and trying again?

**Comment by mwagena** [comment]
well actually, with `full` the first time the widget indeed shows as excpected but after reloading the page the previously checked checkboxes are unchecked and the submit button doesn't work either.

**Comment by mwagena** [comment]
in addition, clearing cache creates the same effect, with fresh cache the checkbox is checked and after a reload it isnt

**Comment by duncanmcclean** [comment]
Have you published any views to your site's `resources/views/vendor` directory.

**Comment by mwagena** [comment]
yes i have published the views, tried it with both my modified view but also with a copy of your view from the vendor directory also i have wrapped the cookie notice tags inside the nocache tag.

I find it strange too, but it definitely makes a different when switching from `full` to `half`.

**Comment by duncanmcclean** [comment]
Can you try removing your published views completley?

**Comment by mwagena** [comment]
Yes i have published the view to the mentioned directory, no difference besides css classnames. also i have wrapped the tag inside the nocache tag..
You aren't able to reproduce?

**Comment by duncanmcclean** [comment]
>  You aren't able to reproduce?

Nope, the widget seems to be working fine for me with full-measure static caching. Are you able to reproduce the issue on a fresh site?

**Comment by duncanmcclean** [comment]
> also i have wrapped the tag inside the nocache tag..

Oh, don't do that.
